on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello public
    steps:
      - name: Hello world action step
        id: hello
        uses: BorklerCanCode/ex250307a@v2
        with:
          who-to-greet: 'Bonnie Borko'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
