name: Release
on:
  push:
    tags:
      - v*

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: [self-hosted, linux, arm64, ubuntu-latest]

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4.1.1
        with:
          # if we release often, there will be no more than this amount of commits in a release
          fetch-depth: 50

      - name: Setup Node
        uses: actions/setup-node@v4.0.1
        with:
          node-version: "20"

      - uses: ncipollo/release-action@v1.13.0
        id: release
        with:
          draft: ${{ contains(github.ref, '-draft') }}
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-alpha') || contains(github.ref, '-beta') }}
          generateReleaseNotes: true
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Workflow notices
        run: echo "::notice title=Release::${{ steps.release.outputs.html_url }}"

